# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.22)
{
  # A helpful description of your flake
  description = "flake for my professional blog";

  # Flake inputs
  inputs = {
    pre-commit-hooks.url = "github:cachix/git-hooks.nix";
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";
  };

  # Flake outputs that other flakes can use
  outputs =
    {
      self,
      flake-schemas,
      nixpkgs,
      pre-commit-hooks,
    }:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" ];
      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            pkgs = import nixpkgs { inherit system; };
          }
        );
    in
    {
      # Schemas tell Nix about the structure of your flake's outputs
      schemas = flake-schemas.schemas;

      # Development environments
      devShells = forEachSupportedSystem (
        { pkgs }:
        {
          default = pkgs.mkShell {
            # Pinned packages available in the environment
            packages = with pkgs; [
              nil

              hugo
              djlint
            ];

            inherit (self.checks.${pkgs.system}.pre-commit-check) shellHook;
            buildInputs = self.checks.${pkgs.system}.pre-commit-check.enabledPackages;
          };
        }
      );

      checks = forEachSupportedSystem (
        { pkgs }:
        {
          pre-commit-check = pre-commit-hooks.lib.${pkgs.system}.run {
            src = ./.;
            hooks = {
              # check nix code
              nil.enable = true;
              # check that secrets aren't committed to the repository
              pre-commit-hook-ensure-sops.enable = true;
              ripsecrets.enable = true;
              # self-explanatory
              check-toml.enable = true;
              # lint template files, go templates for my use-case
              djlint = {
                enable = true;
                name = "djlint - template linter";
                entry = "${pkgs.djlint}/bin/djlint --profile=golang";
                files = "\\.html$";
              };
              # check for broken links
              mkdocs-linkcheck.enable = true;
              # check markdown format is correct
              markdownlint.enable = true;
              # other checkers
              check-case-conflicts.enable = true;
              end-of-file-fixer.enable = true;
              trim-trailing-whitespace.enable = true;
            };
          };
        }
      );
    };
}
