baseURL = 'https://jorgearaya.dev/'
languageCode = 'en'
title = 'Jorge Araya | Freelance Software Engineer'
theme = 'coder'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
pluralizeListTitles = false
enableEmoji = true

[pagination]
pagerSize = 20

[markup.highlight]
style = "paraiso-dark"

[params]
  author = "Jorge Araya"
  info = "I build scalable backend systems and APIs with Go & Python"
  description = "My personal website"
  keywords = "blog,developer,personal,freelancer,software engineer"
  avatarurl = "images/me.jpg"
  images = ["images/site cover.jpg"]

  faviconSVG = "images/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]
[params.goatCounter]
  code = "vekdddjcxj2dgzazsr"

[[params.social]]
  twitter = "elzorrorebelde"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[languages.en]
languageName = ":us:"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/shackra/"
  target = "_blank"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/shackra/"
  target = "_blank"
[[params.social]]
  name = "𝕏"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://x.com/elzorrorebelde/"
  target = "_blank"
[[params.social]]
  name = "Stack Overflow"
  icon = "fa-brands fa-stack-overflow fa-2x"
  weight = 4
  url = "https://stackoverflow.com/users/2020214/shackra"
  target="_blank"

# Menu links
[[languages.en.menu.main]]
  name = "Résumé"
  weight = 1
  url = "resume/"
[[languages.en.menu.main]]
  name = "Blog"
  weight = 2
  url  = "blog/"
[[languages.en.menu.main]]
  name = "Portfolio"
  weight = 3
  url = "portfolio/"
[[languages.en.menu.main]]
  name = "Contact"
  weight = 4
  url = "https://cal.com/jorgean/30min"

# Español
[languages.es]
languageName = "🇨🇷"
title = "Jorge Araya | Ingeniero de software freelance"

[languages.es.params]
author = "Jorge Araya"
info = "Desarrollo sistemas backend escalables y APIs con Go y Python"
description = "Mi sitio web personal"
keywords = "blog,desarrollador,personal,freelancer,ingeniero de software"

[[languages.es.menu.main]]
  name = "CV"
  weight = 1
  url = "resume/"
[[languages.es.menu.main]]
  name = "Bitácora"
  weight = 2
  url  = "blog/"
[[languages.es.menu.main]]
  name = "Portafolio"
  weight = 3
  url = "portfolio/"
[[languages.es.menu.main]]
  name = "Contacto"
  weight = 4
  url = "https://cal.com/jorgean/30min"
