name: Run Checks

on:
  push:
    branches:
      - '**'  # Esto incluye todas las ramas

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - name: Install Nix
        uses: cachix/install-nix-action@v24
      - name: Run nix flake check
        run: nix flake check --all-systems
